[workspace]
members = [
    'node',
    'runtime',
]
exclude = [
    # 'contracts/market',
    # 'contracts/nft',
    # 'contracts/SolarFT',
    # 'contracts/SolarNFTMarket',
    # 'contracts/kuggamax'
]
[profile.release]
panic = 'unwind'
