[workspace]
members = [
    'node',
    'runtime',
    'pallets/nft',
    'pallets/interlaken',
    'contracts/market',
    'contracts/nft',
]
exclude = [
    'contracts/SolarFT',
    'contracts/SolarNFTMarket',
]
[profile.release]
panic = 'unwind'
