version: '3'
services:
  node_alice:
    ports:
      - "30333:30333"
      - "9933:9933"
      - "9944:9944"
      - "9615:9615"
    image: registry.paradeum.com/netwarps/solarchain:latest
    volumes:
      - "solarchain-data-alice:/data"
    command: |
      --chain=local
      --alice
      -d /data
      --unsafe-rpc-external
      --unsafe-ws-external
      --rpc-cors all
      --prometheus-external
      --node-key 0000000000000000000000000000000000000000000000000000000000000001
    networks:
      testing_net:
        ipv4_address: 172.28.1.1

  node_bob:
    ports:
      - "30344:30333"
      - "9935:9933"
      - "9945:9944"
      - "29615:9615"
    image: registry.paradeum.com/netwarps/solarchain:latest
    volumes:
      - "solarchain-data-bob:/data"
    links:
      - "node_alice:alice"
    command: |
      --chain=local
      --bob
      -d /data
      --unsafe-rpc-external
      --unsafe-ws-external
      --rpc-cors all
      --prometheus-external
      --bootnodes '/ip4/172.28.1.1/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp'
    networks:
      testing_net:
        ipv4_address: 172.28.1.2

volumes:
  solarchain-data-alice:
  solarchain-data-bob:

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16